[package]
name = "czkawka-tauri"
version = "0.1.0"
edition = "2021"
authors = ["shixinhuang99 <shixinhuang99@gmail.com>"]
description = "Another gui of Czkawka built for MacOs and Windows"
repository = "https://github.com/shixinhuang99/czkawka-tauri"
license = "MIT"
publish = false

[[bin]]
name = "CzkawkaTauri"
path = "src/main.rs"

[dependencies]
czkawka_core = "8.0.0"
home = "0.5.11"
opener = "0.7.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }

[build-dependencies]
tauri-build = { version = "2", features = [] }
