[package]
name = "czkawka-tauri"
version = "0.1.0"
edition = "2021"
authors = ["shixinhuang99 <shixinhuang99@gmail.com>"]
description = "Another GUI of Czkawka built for macOS and Windows"
repository = "https://github.com/shixinhuang99/czkawka-tauri"
license = "MIT"
publish = false

[[bin]]
name = "CzkawkaTauri"
path = "src/main.rs"

[dependencies]
crossbeam-channel = "0.5.14"
czkawka_core = "8.0.0"
home = "0.5.11"
rayon = "1.10.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2.2.0"
tauri-plugin-opener = "2.2.6"

[build-dependencies]
tauri-build = { version = "2", features = [] }
