name: bundle-dry-run

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  bundle:
    runs-on: macos-13
    name: bundle dry run

    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "aarch64-apple-darwin"

      - name: macos bundles
        run: |
          npm i pnpm -g
          pnpm i
          node --run build:ui
          node --run build:tauri
          node --run bundle
          node --run build:tauri:mac-arm64
          node --run bundle:mac-arm64
