name: bundle-dry-run

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  bundle:
    runs-on: macos-latest
    name: bundle dry run

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "aarch64-apple-darwin"

      - name: macos bundles
        run: |
          npm i pnpm -g
          pnpm i
          node --run build:ui
          node --run build:tauri
          node --run bundle
